In [5]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.core.operations import SymmOp
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.electronic_structure.plotter import BSPlotter
from pymatgen.phonon.plotter import PhononBSPlotter
from jupyter_jsmol.pymatgen import quick_view
from lmapr1492 import plot_brillouin_zone, get_plot_bs, get_plot_dos, get_plot_bs_and_dos, get_branch_wavevectors
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from jupyter_jsmol import JsmolView
from ipywidgets import Layout, widgets, interact
from IPython.display import display

In [6]:
mp_key = "0TSH4JPmYApoWkybWbmreInYgdHzp5GT"
mp_id = "mp-29678"

In [7]:
with MPRester(mp_key) as m:
    prim_struc = m.get_structure_by_material_id(mp_id)
    el_dos = m.get_dos_by_material_id(mp_id)
conv_struc = SpacegroupAnalyzer(prim_struc).get_conventional_standard_structure()
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations()

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Retrieving ElectronicStructureDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

# Structure symmetry

In [8]:
print("Première opération de symétrie : Rotation d'ordre 6 (x, y, z)->(-y, -x+y, -z)")
i_atom = 3
i_symmop = 4
symmop = symmops[i_symmop - 1]
print(symmop)
pos_init = conv_struc.sites[i_atom -1].frac_coords
print("Position initiale : ",pos_init)
pos_final = symmop.operate(pos_init)
print("Position après symétrie : ",pos_final)
print("color lightsalmon : Argon")
print("color gold : Bismuth")
print("color palegreen : Sulfur")

view = quick_view(prim_struc, "packed", conventional = True)
display(view)
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')
view.script('select argon; color lightsalmon')
view.script('select bismuth; color gold')
view.script('select sulfur; color palegreen')
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')

Première opération de symétrie : Rotation d'ordre 6 (x, y, z)->(-y, -x+y, -z)
Rot:
[[ 0.  1.  0.]
 [-1.  1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]
Position initiale :  [0.66666667 0.33333333 0.83333333]
Position après symétrie :  [ 0.33333333 -0.33333333 -0.83333333]
color lightsalmon : Argon
color gold : Bismuth
color palegreen : Sulfur


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [18]:
print("Deuxième opération de symétrie : plan de glissment axial (x, y, z)->(-y, -x, z) + c/2")
i_atom = 2
i_symmop = 20
symmop = symmops[i_symmop - 1]
print(symmop)
pos_init = conv_struc.sites[i_atom -1].frac_coords
print("Position initiale : ",pos_init)
pos_final = symmop.operate(pos_init)
print("Position après symétrie : ",pos_final)
print("color lightsalmon : Argon")
print("color gold : Bismuth")
print("color palegreen : Sulfur")

view = quick_view(prim_struc, "packed", conventional = True)
display(view)
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')
view.script('select argon; color lightsalmon')
view.script('select bismuth; color gold')
view.script('select sulfur; color palegreen')
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')

Deuxième opération de symétrie : plan de glissment axial (x, y, z)->(-y, -x, z) + c/2
Rot:
[[ 0. -1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
tau
[0.66666667 0.33333333 0.33333333]
Position initiale :  [1.  1.  0.5]
Position après symétrie :  [-0.33333333 -0.66666667  0.83333333]
color lightsalmon : Argon
color gold : Bismuth
color palegreen : Sulfur


JsmolView(layout=Layout(align_self='stretch', height='400px'))

In [23]:
print("Troisième opération de symétrie : Réflexion (x, y, z)->(-x+y, y, z) ")
i_atom = 5
i_symmop = 10
symmop = symmops[i_symmop - 1]
print(symmop)
pos_init = conv_struc.sites[i_atom -1].frac_coords
print("Position initiale : ",pos_init)
pos_final = symmop.operate(pos_init)
print("Position après symétrie : ",pos_final)
print("color lightsalmon : Argon")
print("color gold : Bismuth")
print("color palegreen : Sulfur")

view = quick_view(prim_struc, "packed", conventional = True)
display(view)
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')
view.script('select argon; color lightsalmon')
view.script('select bismuth; color gold')
view.script('select sulfur; color palegreen')
view.script('draw SYMOP ' + str(i_symmop) + ' {atomno = ' + str(i_atom) + '}')

Troisième opération de symétrie : Réflexion (x, y, z)->(-x+y, y, z) 
Rot:
[[-1.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]
Position initiale :  [0.66666667 0.33333333 0.33333333]
Position après symétrie :  [-0.33333333  0.33333333  0.33333333]
color lightsalmon : Argon
color gold : Bismuth
color palegreen : Sulfur


JsmolView(layout=Layout(align_self='stretch', height='400px'))